// Full list of countries with flags and phone codes
export const COUNTRIES = [
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', phoneCode: 'AE' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', phoneCode: 'SA' },
  { code: 'IN', name: 'India', flag: '🇮🇳', phoneCode: 'IN' },
  { code: 'US', name: 'United States', flag: '🇺🇸', phoneCode: 'US' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', phoneCode: 'GB' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', phoneCode: 'CA' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', phoneCode: 'AU' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', phoneCode: 'DE' },
  { code: 'FR', name: 'France', flag: '🇫🇷', phoneCode: 'FR' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', phoneCode: 'IT' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', phoneCode: 'ES' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', phoneCode: 'JP' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', phoneCode: 'KR' },
  { code: 'CN', name: 'China', flag: '🇨🇳', phoneCode: 'CN' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', phoneCode: 'SG' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', phoneCode: 'MY' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', phoneCode: 'TH' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', phoneCode: 'ID' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', phoneCode: 'PH' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', phoneCode: 'VN' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', phoneCode: 'PK' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', phoneCode: 'BD' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', phoneCode: 'LK' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', phoneCode: 'NP' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', phoneCode: 'EG' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', phoneCode: 'NG' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', phoneCode: 'ZA' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', phoneCode: 'KE' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', phoneCode: 'GH' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', phoneCode: 'MA' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', phoneCode: 'TN' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', phoneCode: 'BR' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', phoneCode: 'MX' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', phoneCode: 'AR' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', phoneCode: 'CL' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', phoneCode: 'CO' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', phoneCode: 'PE' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', phoneCode: 'TR' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', phoneCode: 'RU' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', phoneCode: 'NL' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', phoneCode: 'BE' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', phoneCode: 'CH' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', phoneCode: 'AT' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', phoneCode: 'SE' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', phoneCode: 'NO' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', phoneCode: 'DK' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', phoneCode: 'FI' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', phoneCode: 'PL' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', phoneCode: 'PT' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', phoneCode: 'IE' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', phoneCode: 'NZ' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', phoneCode: 'QA' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', phoneCode: 'KW' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', phoneCode: 'BH' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', phoneCode: 'OM' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', phoneCode: 'JO' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', phoneCode: 'LB' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', phoneCode: 'IQ' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', phoneCode: 'IL' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', phoneCode: 'HK' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', phoneCode: 'TW' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', phoneCode: 'CZ' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', phoneCode: 'HU' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', phoneCode: 'RO' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', phoneCode: 'GR' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', phoneCode: 'UA' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', phoneCode: 'HR' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', phoneCode: 'RS' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', phoneCode: 'BG' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', phoneCode: 'SK' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', phoneCode: 'LT' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', phoneCode: 'LV' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', phoneCode: 'EE' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', phoneCode: 'MT' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', phoneCode: 'CY' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', phoneCode: 'LU' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', phoneCode: 'IS' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', phoneCode: 'MM' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', phoneCode: 'KH' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', phoneCode: 'LA' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', phoneCode: 'ET' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', phoneCode: 'TZ' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', phoneCode: 'UG' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', phoneCode: 'RW' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', phoneCode: 'DZ' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', phoneCode: 'LY' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', phoneCode: 'SD' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', phoneCode: 'EC' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', phoneCode: 'UY' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', phoneCode: 'PY' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', phoneCode: 'BO' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', phoneCode: 'VE' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', phoneCode: 'CR' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', phoneCode: 'PA' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', phoneCode: 'DO' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', phoneCode: 'GT' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', phoneCode: 'CU' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', phoneCode: 'JM' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', phoneCode: 'TT' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', phoneCode: 'FJ' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', phoneCode: 'MV' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', phoneCode: 'BN' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', phoneCode: 'MN' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', phoneCode: 'GE' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', phoneCode: 'AM' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', phoneCode: 'AZ' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', phoneCode: 'KZ' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', phoneCode: 'UZ' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', phoneCode: 'AF' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', phoneCode: 'IR' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', phoneCode: 'PS' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', phoneCode: 'YE' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', phoneCode: 'SY' },
].sort((a, b) => a.name.localeCompare(b.name));

// Major cities by country code
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Al Ain'],
  SA: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Dhahran', 'Tabuk', 'Abha', 'Taif', 'Jubail', 'Yanbu'],
  IN: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow', 'Chandigarh', 'Kochi', 'Goa', 'Indore', 'Coimbatore', 'Surat', 'Nagpur', 'Thiruvananthapuram', 'Visakhapatnam', 'Bhopal'],
  US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'San Francisco', 'San Diego', 'Dallas', 'Austin', 'Miami', 'Seattle', 'Denver', 'Boston', 'Nashville', 'Portland', 'Las Vegas', 'Atlanta', 'Orlando', 'Minneapolis', 'Detroit'],
  GB: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Edinburgh', 'Liverpool', 'Bristol', 'Cardiff', 'Belfast', 'Newcastle', 'Nottingham', 'Sheffield', 'Cambridge', 'Oxford', 'Brighton', 'Bath'],
  CA: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Quebec City', 'Halifax', 'Victoria'],
  AU: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Hobart', 'Darwin'],
  DE: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresden'],
  FR: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Bordeaux', 'Strasbourg', 'Lille', 'Nantes'],
  IT: ['Rome', 'Milan', 'Naples', 'Florence', 'Venice', 'Turin', 'Bologna', 'Palermo', 'Genoa'],
  ES: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Bilbao', 'Málaga', 'Zaragoza', 'Palma'],
  JP: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Hiroshima'],
  KR: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Jeju'],
  SG: ['Singapore'],
  MY: ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Malacca', 'Ipoh', 'Kota Kinabalu', 'Kuching'],
  TH: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai', 'Khon Kaen', 'Nakhon Ratchasima'],
  QA: ['Doha', 'Al Wakrah', 'Al Khor', 'Lusail'],
  KW: ['Kuwait City', 'Hawalli', 'Salmiya', 'Fahaheel', 'Jahra'],
  BH: ['Manama', 'Muharraq', 'Riffa', 'Hamad Town'],
  OM: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'],
  JO: ['Amman', 'Zarqa', 'Irbid', 'Aqaba'],
  LB: ['Beirut', 'Tripoli', 'Sidon', 'Jounieh', 'Byblos'],
  EG: ['Cairo', 'Alexandria', 'Giza', 'Sharm El Sheikh', 'Hurghada', 'Luxor', 'Aswan'],
  NG: ['Lagos', 'Abuja', 'Port Harcourt', 'Kano', 'Ibadan'],
  ZA: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth'],
  KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Curitiba', 'Recife', 'Fortaleza', 'Belo Horizonte'],
  MX: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancún', 'Puebla', 'Tijuana'],
  TR: ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Bursa', 'Adana'],
  PK: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Peshawar', 'Multan'],
  BD: ['Dhaka', 'Chittagong', 'Sylhet', 'Khulna', 'Rajshahi'],
  NL: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'],
  CH: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'],
  NZ: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Queenstown'],
  PH: ['Manila', 'Cebu', 'Davao', 'Makati', 'Quezon City'],
  ID: ['Jakarta', 'Bali', 'Surabaya', 'Bandung', 'Yogyakarta', 'Medan'],
  VN: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Nha Trang', 'Hue'],
  CN: ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Nanjing'],
  HK: ['Hong Kong Island', 'Kowloon', 'New Territories'],
  RU: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan'],
};
